In [2]:
from datasets import load_dataset

dataset_train = load_dataset("McAuley-Lab/Amazon-Reviews-2023" , 'raw_review_Software' , split='full[2195000:2200000]')
dataset_val = load_dataset("McAuley-Lab/Amazon-Reviews-2023" , 'raw_review_Software' , split='full[599900:600000]')
dataset_test = load_dataset("McAuley-Lab/Amazon-Reviews-2023" , 'raw_review_Software' , split='full[699900:700000]')
dataset_test

/opt/conda/lib/python3.10/site-packages/datasets/load.py:1461: FutureWarning: The repository for McAuley-Lab/Amazon-Reviews-2023 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/McAuley-Lab/Amazon-Reviews-2023
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


Generating full split: 0 examples [00:00, ? examples/s]

/opt/conda/lib/python3.10/site-packages/datasets/load.py:1461: FutureWarning: The repository for McAuley-Lab/Amazon-Reviews-2023 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/McAuley-Lab/Amazon-Reviews-2023
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


Dataset({
    features: ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase'],
    num_rows: 100
})

In [3]:
dataset_test[50]

{'rating': 5.0,
 'title': 'Great',
 'text': 'Great',
 'images': [],
 'asin': 'B06Y66GB9T',
 'parent_asin': 'B06Y66GB9T',
 'user_id': 'AHAOZODJISG3VGEPREVRDVUAGMPA',
 'timestamp': 1559611858977,
 'helpful_vote': 12,
 'verified_purchase': True}

In [4]:
import torch
device = 'cpu'
if torch.cuda.is_available():
    device = 'cuda'

In [5]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")

tokenizer.add_special_tokens({'pad_token': '[PAD]'})
def tokenize_function(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True)

tokenized_datasets_train = dataset_train.map(tokenize_function, batched=True)
tokenized_datasets_val = dataset_val.map(tokenize_function, batched=True)
tokenized_datasets_test = dataset_test.map(tokenize_function, batched=True)


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [14]:
tokenized_datasets_test

Dataset({
    features: ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 100
})

In [7]:
from transformers import AutoModelForMaskedLM
from transformers import Trainer , TrainingArguments , AutoTokenizer
from transformers import DataCollatorForLanguageModeling
from accelerate import Accelerator

acc = Accelerator()
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)

model = AutoModelForMaskedLM.from_pretrained("google-bert/bert-base-uncased")
model = acc.prepare(model)

2024-05-26 23:09:00.321650: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-26 23:09:00.321755: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-26 23:09:00.436220: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at google-bert/bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [8]:
torch.cuda.empty_cache()
# Define training arguments
training_args = TrainingArguments(
    output_dir="./results_bert1",  # Output directory for saved model and logs
    num_train_epochs=3,     # Number of training epochs
    per_device_train_batch_size=4,  # Batch size for training 
    per_device_eval_batch_size=4,   # Batch size for evaluation
    learning_rate=2e-5,            # Learning rate
    warmup_steps=500,              # Number of warmup steps (optional)
    save_strategy="epoch",        # Save checkpoint after each epoch
    evaluation_strategy="epoch",
)

# Define the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets_train,
    eval_dataset=tokenized_datasets_val,
    data_collator=data_collator
)

# Fine-tune the model
trainer.train()

/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

  ········································


wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


TrainOutput(global_step=3750, training_loss=0.039280444742242494, metrics={'train_runtime': 2214.4185, 'train_samples_per_second': 6.774, 'train_steps_per_second': 1.693, 'total_flos': 3948072192000000.0, 'train_loss': 0.039280444742242494, 'epoch': 3.0})

In [9]:
model.save_pretrained('./fine_tuned_bert1')
tokenizer.save_pretrained('./fine_tuned_bert1')


('./fine_tuned_bert1/tokenizer_config.json',
 './fine_tuned_bert1/special_tokens_map.json',
 './fine_tuned_bert1/vocab.txt',
 './fine_tuned_bert1/added_tokens.json',
 './fine_tuned_bert1/tokenizer.json')

In [15]:
import torch
from sklearn.metrics import accuracy_score , precision_score
torch.cuda.empty_cache()

test_results = trainer.evaluate(tokenized_datasets_test) 
print(f"Test Results: {test_results}")

test_predictions = trainer.predict(tokenized_datasets_test ).predictions.argmax(axis=-1)
print(test_predictions)
test_labels = tokenized_datasets_test['input_ids']

test_accuracy = accuracy_score(test_labels, test_predictions)
test_precision = precision_score(test_labels, test_predictions, average='weighted')

print(f"Test Accuracy: {test_accuracy}")
print(f"Test Precision: {test_precision}")

Test Results: {'eval_loss': 3.316721267765388e-05, 'eval_runtime': 2.3227, 'eval_samples_per_second': 43.054, 'eval_steps_per_second': 10.763, 'epoch': 3.0}
[[ 101 1996 4268 ... 1524 1524 6052]
 [ 101 7929 1012 ... 1529 1524 6052]
 [ 101 1045 2031 ... 1524 1524 7953]
 ...
 [ 101 1045 4149 ... 1524 1524 6052]
 [ 101 3733 2438 ... 1524 1524 1996]
 [ 101 2293 2009 ... 1524 1524 1524]]


ValueError: multiclass-multioutput is not supported